name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: arcdps_food_reminder
          path: target/release/arcdps_food_reminder.dll
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/release/arcdps_food_reminder.dll
          overwrite: true
